version: '3'
services:
  feed-master-now:
    build: .
    image: umputun/feed-master-now
    container_name: feed-master-now
    volumes:
      - ./config-politics:/srv/config
    expose:
      - 8080
    links:
      - mongodb
    entrypoint: /srv/exec.sh 8080
    environment:
      - VIRTUAL_HOST=echo-now.burdukov.by
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=echo-now.burdukov.by
      - LETSENCRYPT_EMAIL=chippcheg@gmail.com
    restart: unless-stopped
  feed-master-later:
    build: .
    image: umputun/feed-master-later
    container_name: feed-master-later
    volumes:
      - ./config-history:/srv/config
    expose:
      - 8080
    links:
      - mongodb
    entrypoint: /srv/exec.sh 8080
    environment:
      - VIRTUAL_HOST=echo-later.burdukov.by
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=echo-later.burdukov.by
      - LETSENCRYPT_EMAIL=chippcheg@gmail.com
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongo:/data/db
    command: mongod --smallfiles --noprealloc
    restart: unless-stopped
networks:
  default:
    external:
      name: nginxproxy_default
