version: '3'
services:
  feed-master:
    build: .
    image: umputun/feed-master
    container_name: feed-master
    volumes:
      - ./config:/srv/config
    ports:
      - 8099:8099
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongo:/data/db
    # ports:
    #   - 27017:27017
    command: mongod --smallfiles --noprealloc
