version: '3'
services:
  feed-master:
    build: .
    image: umputun/feed-master
    container_name: feed-master
    volumes:
      - ./config:/srv/config
    expose:
      - 8080
    links:
      - mongodb
    entrypoint: /srv/exec.sh 8080
    environment:
      - VIRTUAL_HOST=echo.burdukov.by
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=echo.burdukov.by
      - LETSENCRYPT_EMAIL=chippcheg@gmail.com
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongo:/data/db
    command: mongod --smallfiles --noprealloc
    restart: unless-stopped
networks:
  default:
    external:
      name: nginxproxy_default
